import Sidebar from '@/app/components/Sidebar';

export const metadata = {
  title: 'Startex Hub | Businessman Services',
  description: 'Generated by create next app',
};


export default function AdminLayout({ children }) {
  return (
   <div className="flex flex-col md:flex-row antialiased  text-white min-h-screen">
  <Sidebar />
  <main className="flex-1 pt-16 px-4">
    {children}
  </main>
</div>
  );
}

