import './globals.css';
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // ✅ All weights
  variable: '--font-poppins',
  display: 'swap',
});

export const metadata = {
  title: 'Startex Hub | Businessman Services',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
